apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007  # 외부에서 접근 가능하도록 설정
